import os
import re
from typing import List, Dict, Optional, Union, Set
from pathlib import Path
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import StrOutputParser
from tenacity import retry, stop_after_attempt, wait_exponential
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from collections import OrderedDict
LANGCHAIN_AVAILABLE = True

from prompts import (
    SECTION_GENERATION_SYSTEM_PROMPT,
    SECTION_GENERATION_USER_TEMPLATE,
    SECTION_GUIDELINES,
    format_context_chunks
)

def mock_generate_section(section_title: str, context_chunks: List[Dict]) -> str:
    """
    Mock 版本的章节生成函数，用于 Sprint 2 流程测试
    
    Args:
        section_title: 章节标题
        context_chunks: 检索到的上下文块（mock 中仅用于统计数量）
    
    Returns:
        固定格式的模拟内容
    """
    return f"""## {section_title}

This is a MOCK generated section for testing the pipeline connectivity.

### Overview

The content generation module has been successfully integrated into the workflow.

### Key Points from Context

- Number of context chunks received: {len(context_chunks)}
- Section title: {section_title}
- This mock content will be replaced with actual LLM-generated content in Sprint 2

### Placeholder References

[1] Mock Reference - Testing Only

---
*This section was generated by the mock generator. For real content, configure LLM and implement SectionGenerator.*
"""

class SectionGenerator:
    def __init__(self, model_name: str = "deepseek-r1:1.5b", temperature: float = 0.1):
        # 1. 初始化 Ollama（无 API Key）
        self.llm = ChatOllama(model=model_name, 
                              temperature=temperature, 
                              num_predict=4096)
        
        # 2. 包装重试
        self._llm_with_retry = retry(
            stop=stop_after_attempt(3),
            wait=wait_exponential(multiplier=1, min=2, max=10)
        )(self.llm.invoke)
        
        # 3. 构建链（与 Sprint 1 完全相同）
        self.chain = self._build_chain()
    
    def _build_chain(self):
        prompt = ChatPromptTemplate.from_messages([
            ("system", SECTION_GENERATION_SYSTEM_PROMPT),
            ("human", SECTION_GENERATION_USER_TEMPLATE)
        ])
        # 使用带重试的 invoke
        return prompt | self._llm_with_retry | StrOutputParser()
    
    def generate_section(self, section_title, context_chunks: List[Dict], 
                         subsections: Optional[List[str]] = None, 
                         guidelines: Optional[str] = None) -> str:
        """生成单个章节"""
        # 格式化上下文，为每个chunk添加索引
        formatted_chunks = format_context_chunks(context_chunks)
        
        # 确定子节列表
        if not subsections:
            subsections = ["Overview", "Key Contributions"]
        
        subsections_str = ", ".join(subsections)
        
        # 获取章节写作指导
        if not guidelines:
            # 尝试从 SECTION_GUIDELINES 中匹配
            section_key = section_title.lower().split()[0]
            guidelines = SECTION_GUIDELINES.get(section_key, "Write a comprehensive academic section based on the provided context.")
        
        # 调用生成链
        response = self.chain.invoke({
            "section_title": section_title,
            "subsections": subsections_str,
            "context_chunks": formatted_chunks,
            "section_guidelines": guidelines
        })
        
        return response.strip()

    
    def generate_outline(
        self,
        topic: str,
        paper_summaries: str,
        prompt_version: str = "V2"
    ) -> str:
        """
        生成综述论文大纲（JSON 格式）
        
        Args:
            topic: 研究主题
            paper_summaries: 格式化后的论文摘要列表
            prompt_version: 使用的 Prompt 版本，可选 "V1", "V2", "V3"
        
        Returns:
            LLM 返回的 JSON 字符串
        """
        from prompts import OUTLINE_PROMPT_V1, OUTLINE_PROMPT_V2, OUTLINE_PROMPT_V3
        
        prompt_map = {
            "V1": OUTLINE_PROMPT_V1,
            "V2": OUTLINE_PROMPT_V2,
            "V3": OUTLINE_PROMPT_V3
        }
        prompt_template = prompt_map.get(prompt_version, OUTLINE_PROMPT_V2)
        
        # 构建用户消息
        user_message = prompt_template.format(
            topic=topic,
            paper_summaries=paper_summaries
        )
        
        # 调用 LLM（使用相同模型，但允许更高温度以增加结构多样性）
        response = self.llm.invoke(user_message)
        return response.content
    
    def generate_full_survey(
        self,
        title: str,
        outline: Dict,  # 大纲，包含 sections 列表
        context_chunks_by_section: Dict[str, List[Dict]],  # 每个章节对应的检索结果
        metadata_store: Dict[int, Dict],
        output_path: Optional[str] = None
    ) -> str:
        """
        生成完整的综述论文

        Args:
            title: 论文标题
            outline: 大纲字典，如 {"sections": [{"title": "Intro", ...}]}
            context_chunks_by_section: 每个章节的检索上下文
            metadata_store: 论文元数据
            output_path: 如果提供，保存到文件

        Returns:
            完整的 Markdown 字符串
        """
        chapters = {}
        for section_info in outline.get("sections", []):
            section_title = section_info["title"]
            context = context_chunks_by_section.get(section_title, [])
            # 调用已有的章节生成方法
            content = self.generate_section(section_title, context)
            chapters[section_title] = content

        # 整合
        final_md = finalize_survey(title, chapters, metadata_store, include_toc=True)

        if output_path:
            save_survey_to_file(output_path, final_md)

        return final_md
    
def extract_all_citations_from_chapters(chapters: Dict[str, str]) -> List[int]:
    """
    从所有章节内容中提取所有引用索引，并按首次出现顺序返回
    """
    citation_order = []
    seen = set()
    # 正则匹配 [数字] 或 [数字,数字] 等，这里简单提取所有数字
    pattern = r'\[(\d+)\]'
    for content in chapters.values():
        for match in re.finditer(pattern, content):
            idx = int(match.group(1))
            if idx not in seen:
                seen.add(idx)
                citation_order.append(idx)
    return citation_order

def generate_table_of_contents(chapters: Dict[str, str]) -> str:
    """
    根据章节内容生成 Markdown 目录
    提取每个章节内容中的一级标题（以 # 开头，但不是 ## 开头）
    """
    toc_lines = ["## Table of Contents\n"]
    for title, content in chapters.items():
        # 从内容中提取第一个一级标题（如果存在），否则使用传入的章节标题
        match = re.search(r'^# (.+)$', content, re.MULTILINE)
        if match:
            heading = match.group(1)
        else:
            heading = title
        # 生成锚点（小写，空格转连字符）
        anchor = heading.lower().replace(' ', '-').replace('?', '').replace(':', '')
        toc_lines.append(f"- [{heading}](#{anchor})")
    return "\n".join(toc_lines)

def generate_references(citation_indices: List[int], metadata_store: Dict[int, Dict]) -> str:
    """
    根据引用索引列表和元数据存储生成参考文献列表
    metadata_store 格式: {1: {"title": "...", "authors": "...", "year": ..., "url": ...}}
    """
    ref_lines = ["## References\n"]
    for idx in citation_indices:
        meta = metadata_store.get(idx, {})
        title = meta.get("title", "Unknown Title")
        authors = meta.get("authors", "Unknown Author")
        year = meta.get("year", "n.d.")
        url = meta.get("url", "")
        # 根据常见格式生成
        ref_lines.append(f"[{idx}] {authors}. {title}. {year}. {url}".strip())
    return "\n".join(ref_lines)

def finalize_survey(
    title: str,
    chapters: Dict[str, str],
    metadata_store: Dict[int, Dict],
    include_toc: bool = True
) -> str:
    """
    整合完整的综述论文

    Args:
        title: 论文标题
        chapters: 章节字典，键为章节名，值为章节内容（Markdown格式）
        metadata_store: 论文元数据，索引 -> 元数据
        include_toc: 是否生成目录

    Returns:
        完整的 Markdown 格式论文
    """
    document_parts = []

    # 1. 标题
    document_parts.append(f"# {title}\n")

    # 2. 目录（可选）
    if include_toc:
        toc = generate_table_of_contents(chapters)
        document_parts.append(toc + "\n")

    # 3. 正文（按顺序拼接）
    for chapter_title, content in chapters.items():
        # 确保内容不以一级标题开头（因为可能已经包含），但保留原样
        document_parts.append(content)
        document_parts.append("\n")  # 章节间空行

    # 4. 提取所有引用索引并生成参考文献
    citation_indices = extract_all_citations_from_chapters(chapters)
    if citation_indices:
        references = generate_references(citation_indices, metadata_store)
        document_parts.append(references)

    return "\n".join(document_parts)

def save_survey_to_file(output_path: str, final_markdown: str) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(final_markdown)
    print(f"Survey saved to {output_path}")
    
def create_generator(
    model_name: str = "gpt-4o-mini",
    temperature: float = 0.1,
    mock: bool = False
) -> Union[SectionGenerator, callable]:
    """
    工厂函数：创建生成器实例（完整版或 Mock）
    
    Args:
        model_name: 模型名称
        temperature: 温度参数
        mock: 如果为 True，返回 mock_generate_section 函数
    
    Returns:
        SectionGenerator 实例或 mock_generate_section 函数
    """
    if mock:
        return mock_generate_section
    else:
        return SectionGenerator(model_name=model_name, temperature=temperature)
    
if __name__ == "__main__":
    chapters = {
        "Introduction": "# Introduction\nThis is a test [1].",
        "Methods": "# Methods\nWe used [2] and [1]."
    }
    metadata_store = {
        1: {"title": "Paper A", "authors": "Author A", "year": 2020, "url": "http://a.com"},
        2: {"title": "Paper B", "authors": "Author B", "year": 2021, "url": "http://b.com"}
    }
    final = finalize_survey("Test Survey", chapters, metadata_store, include_toc=True)
    print(final)