import os
import re
from typing import List, Dict, Optional, Union
from pathlib import Path

# 尝试导入 LangChain 相关模块（完整版使用）
try:
    from langchain_openai import ChatOpenAI
    from langchain_core.prompts import ChatPromptTemplate
    from langchain_core.output_parsers import StrOutputParser
    LANGCHAIN_AVAILABLE = True
except ImportError:
    LANGCHAIN_AVAILABLE = False
    print("Warning: LangChain not installed. Install with: pip install langchain langchain-openai")

from prompts import (
    SECTION_GENERATION_SYSTEM_PROMPT,
    SECTION_GENERATION_USER_TEMPLATE,
    SECTION_GUIDELINES,
    format_context_chunks
)

def mock_generate_section(section_title: str, context_chunks: List[Dict]) -> str:
    """
    Mock 版本的章节生成函数，用于 Sprint 1 流程测试
    
    Args:
        section_title: 章节标题
        context_chunks: 检索到的上下文块（mock 中仅用于统计数量）
    
    Returns:
        固定格式的模拟内容
    """
    return f"""## {section_title}

This is a MOCK generated section for testing the pipeline connectivity.

### Overview

The content generation module has been successfully integrated into the workflow.

### Key Points from Context

- Number of context chunks received: {len(context_chunks)}
- Section title: {section_title}
- This mock content will be replaced with actual LLM-generated content in Sprint 2

### Placeholder References

[1] Mock Reference - Testing Only

---
*This section was generated by the mock generator. For real content, configure LLM and implement SectionGenerator.*
"""

class SectionGenerator:
    def __init__(self, model_name: str = "gpt-4o-mini", 
                 temperature: float = 0.1,
                 api_key: Optional[str] = None,
                 base_url: Optional[str] = None
                ):
        """
        初始化章节生成器
        Args:
            model_name: LLM 模型名称（OpenAI 兼容接口）
            temperature: 温度参数，低温度减少幻觉
            api_key: API 密钥（若不提供则从环境变量读取）
            base_url: API 基础 URL（用于代理或本地模型
        """
        if not LANGCHAIN_AVAILABLE:
            raise ImportError("LangChain is required for SectionGenerator. Install with: pip install langchain langchain-openai")
        
        # 配置 OpenAI 客户端
        kwargs = {
            "model": model_name,
            "temperature": temperature,
            "max_tokens": 4096
        }
        if api_key:
            kwargs["api_key"] = api_key
        if base_url:
            kwargs["base_url"] = base_url
        
        self.llm = ChatOpenAI(**kwargs)
        self.chain = self._build_chain()
    
    def _build_chain(self):
        """构建生成链：SystemPrompt + UserPrompt + LLM + OutputParser"""
        prompt = ChatPromptTemplate.from_messages([
            ("system", SECTION_GENERATION_SYSTEM_PROMPT),
            ("human", SECTION_GENERATION_USER_TEMPLATE)
        ])
        # 推荐使用 prompt | llm | parser 模式[reference:4]
        return prompt | self.llm | StrOutputParser()
    
    def generate_section(
        self, 
        section_title: str, 
        context_chunks: List[Dict],  # 来自成员B的retrieve()返回结果
        subsections: Optional[List[str]] = None,
        guidelines: Optional[str] = None
    ) -> str:
        """
        生成单个章节的内容
        
        Args:
            section_title: 章节标题
            context_chunks: 检索到的相关文本块，每个块包含content和metadata
            subsections: 该章节需要覆盖的子节列表
            guidelines: 章节写作指导
        
        Returns:
            生成的章节文本（Markdown格式）
        """
        # 格式化上下文，为每个chunk添加索引
        formatted_chunks = self._format_context_chunks(context_chunks)
        
        # 确定子节列表
        if not subsections:
            subsections = ["Overview", "Key Contributions"]
        
        subsections_str = ", ".join(subsections)
        
        # 获取章节写作指导
        if not guidelines:
            # 尝试从 SECTION_GUIDELINES 中匹配
            section_key = section_title.lower().split()[0]
            guidelines = SECTION_GUIDELINES.get(section_key, "Write a comprehensive academic section based on the provided context.")
        
        # 调用链
        response = self.chain.invoke({
            "section_title": section_title,
            "subsections": ", ".join(subsections),
            "context_chunks": formatted_chunks,
            "section_guidelines": guidelines
        })
        
        return response.strip()
    
    def generate_outline(
        self,
        topic: str,
        paper_summaries: str,
        prompt_version: str = "V2"
    ) -> str:
        """
        生成综述论文大纲（JSON 格式）
        
        Args:
            topic: 研究主题
            paper_summaries: 格式化后的论文摘要列表
            prompt_version: 使用的 Prompt 版本，可选 "V1", "V2", "V3"
        
        Returns:
            LLM 返回的 JSON 字符串
        """
        from prompts import OUTLINE_PROMPT_V1, OUTLINE_PROMPT_V2, OUTLINE_PROMPT_V3
        
        prompt_map = {
            "V1": OUTLINE_PROMPT_V1,
            "V2": OUTLINE_PROMPT_V2,
            "V3": OUTLINE_PROMPT_V3
        }
        prompt_template = prompt_map.get(prompt_version, OUTLINE_PROMPT_V2)
        
        # 构建用户消息
        user_message = prompt_template.format(
            topic=topic,
            paper_summaries=paper_summaries
        )
        
        # 调用 LLM（使用相同模型，但允许更高温度以增加结构多样性）
        response = self.llm.invoke(user_message)
        return response.content
    
def create_generator(
    model_name: str = "gpt-4o-mini",
    temperature: float = 0.1,
    mock: bool = False
) -> Union[SectionGenerator, callable]:
    """
    工厂函数：创建生成器实例（完整版或 Mock）
    
    Args:
        model_name: 模型名称
        temperature: 温度参数
        mock: 如果为 True，返回 mock_generate_section 函数
    
    Returns:
        SectionGenerator 实例或 mock_generate_section 函数
    """
    if mock:
        return mock_generate_section
    else:
        return SectionGenerator(model_name=model_name, temperature=temperature)
    
if __name__ == "__main__":
    # 测试 Mock 版本
    print("=== Testing Mock Generator ===")
    mock_result = mock_generate_section(
        "Introduction",
        [{"content": "test", "metadata": {}}]
    )
    print(mock_result)
    
    # 测试完整版（需要设置 OPENAI_API_KEY 环境变量）
    if LANGCHAIN_AVAILABLE and os.getenv("OPENAI_API_KEY"):
        print("\n=== Testing Real Generator ===")
        try:
            generator = SectionGenerator()
            # 模拟检索结果
            mock_chunks = [
                {
                    "content": "Transformers have revolutionized NLP. They use self-attention.",
                    "metadata": {"paper_title": "Attention Is All You Need", "authors": ["Vaswani"]}
                }
            ]
            result = generator.generate_section(
                "Introduction",
                mock_chunks,
                subsections=["Background", "Contributions"],
                guidelines="Introduce the field and state the paper's contributions."
            )
            print(result)
        except Exception as e:
            print(f"Real generator test failed: {e}")
    else:
        print("\nSkipping real generator test: LangChain not available or OPENAI_API_KEY not set.")